version: '3.8'

networks:
  mqtt-network:
    driver: bridge

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    networks:
      - mqtt-network
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./src/mosquitto/config:/mosquitto/config
      - ./src/mosquitto/data:/mosquitto/data
      - ./src/mosquitto/log:/mosquitto/log
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - mqtt-network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: unless-stopped

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    networks:
      - mqtt-network
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    restart: unless-stopped

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    networks:
      - mqtt-network
    ports:
      - "1880:1880"
    volumes:
      - ./src/node-red:/data
    environment:
      - TZ=Etc/UTC
    restart: unless-stopped

volumes:
  mosquitto_config:
  mosquitto_data:
  mosquitto_logs:
  mongodb_data:
  node_red_data:
